import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StockHeader from "@/components/StockHeader";
import MenuTabs from "@/components/MenuTabs";
import StockCache from "@/Context/CacheContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stock Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <StockCache>
          <div className="max-w-screen-lg mx-auto">{children}</div>
        </StockCache>
      </body>
    </html>
  );
}
